type DictShape = Record<string, string>;

const de = {
  "nav.home": "Startseite",
  "nav.dashboard": "Dashboard",
  "nav.admin": "Admin",
  "nav.login": "Anmelden",
  "nav.register": "Registrieren",
  "nav.logout": "Abmelden",
  "nav.backHome": "Zurück zur Startseite",
  "nav.searchPlaceholder": "Stadt, PLZ...",
  "hero.title": "Finden Sie Ihre Traumwohnung",
  "hero.subtitle":
    "Wir suchen für Sie – Sie erhalten Benachrichtigungen in Telegram",
  "hero.cta.register": "Jetzt registrieren",
  "hero.cta.login": "Ich habe schon ein Konto",
  "hero.howItWorks": "So funktioniert's",
  "hero.cta.bottom": "Kostenlos starten",
  "hero.cta.bottomReady": "Bereit, Ihre Suche zu starten?",
  "hero.cta.bottomDesc":
    "Erstellen Sie ein Konto in wenigen Sekunden und erhalten Sie sofort passende Wohnungsangebote in Ihrem Telegram.",
  "hero.badge": "Neue Wohnungen jeden Tag",
  "hero.howItWorks.subtitle": "Drei einfache Schritte zu Ihrer neuen Wohnung",
  "hero.stats.listings": "Wohnungen verfügbar",
  "hero.stats.searchers": "Aktive Suchende",
  "hero.stats.notifications": "Benachrichtigungen",
  "features.search.title": "Suchen",
  "features.search.desc":
    "Wählen Sie Stadt, Preis, Fläche – wir finden passende Wohnungen",
  "features.search.long":
    "Geben Sie Ihre Kriterien ein — Stadt, Preis, Größe und mehr. Wir durchsuchen alle großen Portale für Sie.",
  "features.search.ru":
    "Поиск — Укажите город, цену, площадь. Мы ищем на всех сайтах.",
  "features.compare.title": "Vergleichen",
  "features.compare.desc":
    "Sehen Sie alle Angebote auf einen Blick und vergleichen Sie",
  "features.compare.long":
    "Sehen Sie alle passenden Wohnungen auf einen Blick. Vergleichen Sie Preise, Größen und Lagen schnell und einfach.",
  "features.compare.ru":
    "Сравнение — Все варианты в одном месте. Цены, площадь, район.",
  "features.notify.title": "Benachrichtigen",
  "features.notify.desc":
    "Erhalten Sie sofort eine Nachricht in Telegram, wenn eine passende Wohnung erscheint",
  "features.notify.long":
    "Neue passende Angebote kommen direkt in Ihren Telegram-Chat. Sie verpassen nie wieder eine gute Wohnung.",
  "features.notify.ru":
    "Уведомления — Новые квартиры сразу в Telegram. Ничего не пропустите.",
  "login.title": "Anmelden",
  "login.welcome": "Willkommen zurück bei SucheWohnung",
  "login.email": "E-Mail",
  "login.password": "Passwort",
  "login.submit": "Anmelden",
  "login.submitting": "Wird angemeldet...",
  "login.noAccount": "Noch kein Konto? Registrieren",
  "login.forgotPassword": "Passwort vergessen?",
  "login.failed": "Anmeldung fehlgeschlagen",
  "login.verifyFirst": "Bitte bestätigen Sie zuerst Ihre E-Mail-Adresse.",
  "login.emailPlaceholder": "ihre@email.de",
  "register.title": "Konto erstellen",
  "register.welcome": "Erstellen Sie Ihr Konto bei SucheWohnung",
  "register.email": "E-Mail",
  "register.password": "Passwort",
  "register.confirmPassword": "Passwort bestätigen",
  "register.submit": "Konto erstellen",
  "register.submitting": "Konto wird erstellt...",
  "register.hasAccount": "Bereits registriert? Anmelden",
  "register.failed": "Registrierung fehlgeschlagen",
  "register.passwordMismatch": "Die Passwörter stimmen nicht überein.",
  "register.passwordTooShort":
    "Das Passwort muss mindestens 8 Zeichen lang sein.",
  "register.verifyTitle": "Bitte bestätigen Sie Ihre E-Mail",
  "register.verifySentPrefix": "Wir haben einen Bestätigungslink an",
  "register.verifySentSuffix":
    "gesendet. Nach der Bestätigung können Sie sich anmelden.",
  "register.toLogin": "Zur Anmeldung",
  "register.emailPlaceholder": "ihre@email.de",
  "register.passwordPlaceholder": "Mindestens 8 Zeichen",
  "register.confirmPlaceholder": "Passwort wiederholen",
  "dashboard.title": "Mein Dashboard",
  "dashboard.subtitle": "Verwalten Sie Ihre Suchprofile und Benachrichtigungen",
  "dashboard.telegram.title": "Telegram",
  "dashboard.telegram.connected": "Verbunden",
  "dashboard.telegram.notConnected": "Nicht verbunden",
  "dashboard.telegram.connect": "Mit Telegram verbinden",
  "dashboard.telegram.copyLink": "Link kopieren",
  "dashboard.telegram.linkCopied": "Link kopiert!",
  "dashboard.telegram.connectedNote":
    "Telegram ist verbunden. Benachrichtigungen werden direkt an Ihren Telegram-Chat gesendet.",
  "dashboard.telegram.notConnectedNote":
    "Verbinden Sie Telegram, um Benachrichtigungen zu erhalten.",
  "dashboard.telegram.howToConnect":
    "Klicken Sie auf den Link oder kopieren Sie ihn und öffnen Sie ihn in Telegram. Starten Sie den Bot mit /start.",
  "dashboard.telegram.checking": "Verbindung wird geprüft...",
  "dashboard.profiles": "Suchprofile",
  "dashboard.profiles.empty": "Noch keine Suchprofile",
  "dashboard.profiles.emptyDesc":
    "Erstellen Sie Ihr erstes Suchprofil und wir suchen passende Wohnungen für Sie.",
  "dashboard.profiles.create": "Neues Suchprofil",
  "dashboard.profiles.createFirst": "Erstes Suchprofil erstellen",
  "dashboard.profiles.edit": "Profil bearbeiten",
  "dashboard.profiles.delete": "Löschen",
  "dashboard.profiles.matches": "Treffer ansehen",
  "dashboard.profiles.toggleActive": "Aktivieren",
  "dashboard.profiles.togglePause": "Pausieren",
  "dashboard.profiles.confirmDelete": "Suchprofil wirklich löschen?",
  "dashboard.profiles.active": "Aktiv",
  "dashboard.profiles.paused": "Pausiert",
  "dashboard.profiles.loading": "Wird geladen...",
  "dashboard.profiles.loadError": "Daten konnten nicht geladen werden.",
  "dashboard.profiles.statusError": "Status konnte nicht geändert werden.",
  "dashboard.profiles.deleteError": "Profil konnte nicht gelöscht werden.",
  "profile.name": "Profilname",
  "profile.city": "Stadt",
  "profile.postalCode": "PLZ",
  "profile.radius": "Umkreis (km)",
  "profile.radiusPlaceholder": "z.B. 10",
  "profile.namePlaceholder": "z.B. Berlin Mitte 2-Zimmer",
  "profile.cityPlaceholder": "z.B. Berlin",
  "profile.postalCodePlaceholder": "z.B. 10115",
  "profile.autoCity": "Stadt übernehmen",
  "profile.nameRequired": "Profilname ist erforderlich",
  "profile.notFound": "Profil nicht gefunden",
  "profile.loadError": "Profil konnte nicht geladen werden",
  "profile.updateError": "Profil konnte nicht aktualisiert werden",
  "profile.priceSpan": "Preisspanne (€)",
  "profile.priceMin": "Preis (min)",
  "profile.priceMax": "Preis (max)",
  "profile.areaSpan": "Wohnfläche (m²)",
  "profile.areaMin": "Fläche (min)",
  "profile.areaMax": "Fläche (max)",
  "profile.roomsMin": "Zimmer (min)",
  "profile.amenities": "Ausstattung",
  "profile.balcony": "Balkon",
  "profile.elevator": "Aufzug",
  "profile.parking": "Parkplatz",
  "profile.parkingLabel": "Parkplatz / Garage",
  "profile.pets": "Haustiere erlaubt",
  "profile.notify": "Benachrichtigungen aktivieren",
  "profile.submit": "Profil speichern",
  "profile.submitting": "Wird gespeichert...",
  "profile.cancel": "Abbrechen",
  "profile.createError": "Profil konnte nicht erstellt werden",
  "profile.filtersRequired": "Bitte wählen Sie mindestens einen Filter aus.",
  "profile.validationError": "Bitte prüfen Sie die Filterwerte.",
  "profile.radiusIncomplete":
    "Für den Umkreis sind Lat, Lng und Radius erforderlich.",
  "profile.geoHint":
    "Die Koordinaten des Zentrums werden automatisch aus der PLZ übernommen. Der Radius bestimmt, wie weit rund um das Zentrum gesucht wird.",
  "profile.geoCenter": "Zentrum",
  "profile.numericFilters": "Suchkriterien",
  "profile.price": "Preis",
  "profile.area": "Fläche",
  "profile.rooms": "Zimmer",
  "admin.title": "Admin Panel",
  "admin.stats.users": "Benutzer",
  "admin.stats.listings": "Wohnungen",
  "admin.stats.matches": "Treffer",
  "admin.stats.notifications": "Benachrichtigungen",
  "admin.sources": "Quellen",
  "admin.sources.enabled": "Aktiv",
  "admin.sources.disabled": "Pausiert",
  "admin.sources.listingsCount": "Anzeigen",
  "admin.queues": "Warteschlangen",
  "admin.queues.collect": "Sammeln",
  "admin.queues.match": "Abgleich",
  "admin.queues.notify": "Benachrichtigen",
  "admin.logs": "Letzte Aktivitäten",
  "admin.logs.action": "Aktion",
  "admin.logs.details": "Details",
  "admin.logs.time": "Zeit",
  "admin.logs.empty": "Keine Aktivitäten vorhanden",
  "admin.loading": "Wird geladen...",
  "admin.subtitle": "Systemübersicht und Verwaltung",
  "admin.refresh": "Aktualisieren",
  "admin.sources.empty": "Keine Quellen konfiguriert",
  "admin.sources.breaker": "Breaker",
  "admin.sources.lastRun": "Letzter Lauf",
  "admin.sources.lifecycle": "Lebenszyklus",
  "admin.sources.runStatus": "Status",
  "admin.sources.fetched": "Geholt",
  "admin.sources.new": "Neu",
  "admin.sources.updated": "Aktualisiert",
  "admin.sources.errors": "Fehler",
  "admin.sources.noMetrics": "Keine Laufdaten verfügbar",
  "admin.queues.depth": "Tiefe",
  "admin.queues.waiting": "wartend",
  "admin.queues.delayed": "verzögert",
  "admin.queues.failed": "fehlgeschlagen",
  "admin.health.healthy": "Gesund",
  "admin.health.degraded": "Eingeschränkt",
  "admin.health.failing": "Fehlerhaft",
  "admin.health.paused": "Pausiert",
  "admin.health.unknown": "Unbekannt",
  "footer.text": "© SucheWohnung – Wohnungssuche in Deutschland",
  "footer.description": "Ihr Begleiter bei der Wohnungssuche in Deutschland",
  "footer.links": "Links",
  "footer.contact": "Kontakt",
  "footer.contactText": "Bei Fragen helfen wir Ihnen gerne weiter.",
  "footer.copyright": "© {year} SucheWohnung. Alle Rechte vorbehalten.",
  "common.loading": "Laden...",
  "common.error": "Fehler",
  "common.save": "Speichern",
  "common.active": "Aktiv",
  "common.inactive": "Inaktiv",
  "common.all": "Alle",
  "common.none": "Keine",
  "common.yes": "Ja",
  "common.no": "Nein",
  "common.min": "Min",
  "common.max": "Max",
  "common.paused": "Pausiert",
  "matches.title": "Gefundene Wohnungen",
  "matches.empty": "Noch keine Treffer",
  "matches.price": "Preis",
  "matches.area": "Fläche",
  "matches.rooms": "Zimmer",
  "matches.viewListing": "Anzeigen",
} satisfies DictShape;

const ru: DictShape = {
  "nav.home": "Главная",
  "nav.dashboard": "Поиск",
  "nav.admin": "Админ",
  "nav.login": "Войти",
  "nav.register": "Регистрация",
  "nav.logout": "Выйти",
  "nav.backHome": "На главную",
  "nav.searchPlaceholder": "Город, индекс...",
  "hero.title": "Найдите свою квартиру в Германии",
  "hero.subtitle": "Мы ищем за вас — вы получаете уведомления в Telegram",
  "hero.cta.register": "Зарегистрироваться",
  "hero.cta.login": "У меня уже есть аккаунт",
  "hero.howItWorks": "Как это работает",
  "hero.cta.bottom": "Начать бесплатно",
  "hero.cta.bottomReady": "Готовы начать поиск?",
  "hero.cta.bottomDesc":
    "Создайте аккаунт за несколько секунд и сразу получайте подходящие предложения в Telegram.",
  "hero.badge": "Новые квартиры каждый день",
  "hero.howItWorks.subtitle": "Три простых шага к вашей новой квартире",
  "hero.stats.listings": "Квартир доступно",
  "hero.stats.searchers": "Активных пользователей",
  "hero.stats.notifications": "Уведомлений",
  "features.search.title": "Поиск",
  "features.search.desc":
    "Выберите город, цену, площадь — мы найдём подходящие квартиры",
  "features.search.long":
    "Укажите свои критерии — город, цена, площадь и другие. Мы ищем на всех крупных порталах.",
  "features.search.ru":
    "Поиск — Укажите город, цену, площадь. Мы ищем на всех сайтах.",
  "features.compare.title": "Сравнение",
  "features.compare.desc": "Смотрите все предложения и сравнивайте",
  "features.compare.long":
    "Все подходящие квартиры в одном месте. Сравнивайте цены, площади и районы быстро и удобно.",
  "features.compare.ru":
    "Сравнение — Все варианты в одном месте. Цены, площадь, район.",
  "features.notify.title": "Уведомления",
  "features.notify.desc":
    "Мгновенное сообщение в Telegram, когда появится подходящая квартира",
  "features.notify.long":
    "Новые подходящие предложения приходят прямо в ваш Telegram. Вы больше не пропустите хорошую квартиру.",
  "features.notify.ru":
    "Уведомления — Новые квартиры сразу в Telegram. Ничего не пропустите.",
  "login.title": "Войти",
  "login.welcome": "С возвращением в SucheWohnung",
  "login.email": "Email",
  "login.password": "Пароль",
  "login.submit": "Войти",
  "login.submitting": "Вход...",
  "login.noAccount": "Нет аккаунта? Зарегистрироваться",
  "login.forgotPassword": "Забыли пароль?",
  "login.failed": "Ошибка входа",
  "login.verifyFirst": "Сначала подтвердите вашу электронную почту.",
  "login.emailPlaceholder": "ваш@email.de",
  "register.title": "Создать аккаунт",
  "register.welcome": "Создайте аккаунт в SucheWohnung",
  "register.email": "Email",
  "register.password": "Пароль",
  "register.confirmPassword": "Подтвердите пароль",
  "register.submit": "Создать аккаунт",
  "register.submitting": "Создание аккаунта...",
  "register.hasAccount": "Уже есть аккаунт? Войти",
  "register.failed": "Ошибка регистрации",
  "register.passwordMismatch": "Пароли не совпадают.",
  "register.passwordTooShort": "Пароль должен быть не менее 8 символов.",
  "register.verifyTitle": "Подтвердите вашу электронную почту",
  "register.verifySentPrefix": "Мы отправили ссылку для подтверждения на",
  "register.verifySentSuffix":
    "После подтверждения вы сможете войти.",
  "register.toLogin": "К входу",
  "register.emailPlaceholder": "ваш@email.de",
  "register.passwordPlaceholder": "Минимум 8 символов",
  "register.confirmPlaceholder": "Повторите пароль",
  "dashboard.title": "Мой поиск",
  "dashboard.subtitle": "Управляйте поисковыми профилями и уведомлениями",
  "dashboard.telegram.title": "Telegram",
  "dashboard.telegram.connected": "Подключён",
  "dashboard.telegram.notConnected": "Не подключён",
  "dashboard.telegram.connect": "Подключить Telegram",
  "dashboard.telegram.copyLink": "Копировать ссылку",
  "dashboard.telegram.linkCopied": "Ссылка скопирована!",
  "dashboard.telegram.connectedNote":
    "Telegram подключён. Уведомления будут приходить прямо в ваш чат.",
  "dashboard.telegram.notConnectedNote":
    "Подключите Telegram для получения уведомлений.",
  "dashboard.telegram.howToConnect":
    "Нажмите на ссылку или скопируйте её и откройте в Telegram. Запустите бота командой /start.",
  "dashboard.telegram.checking": "Проверка подключения...",
  "dashboard.profiles": "Поисковые профили",
  "dashboard.profiles.empty": "Пока нет поисковых профилей",
  "dashboard.profiles.emptyDesc":
    "Создайте первый поисковый профиль, и мы найдём подходящие квартиры.",
  "dashboard.profiles.create": "Новый профиль",
  "dashboard.profiles.createFirst": "Создать первый профиль",
  "dashboard.profiles.edit": "Редактировать профиль",
  "dashboard.profiles.delete": "Удалить",
  "dashboard.profiles.matches": "Смотреть совпадения",
  "dashboard.profiles.toggleActive": "Включить",
  "dashboard.profiles.togglePause": "Пауза",
  "dashboard.profiles.confirmDelete": "Удалить поисковый профиль?",
  "dashboard.profiles.active": "Активен",
  "dashboard.profiles.paused": "На паузе",
  "dashboard.profiles.loading": "Загрузка...",
  "dashboard.profiles.loadError": "Не удалось загрузить данные.",
  "dashboard.profiles.statusError": "Не удалось изменить статус.",
  "dashboard.profiles.deleteError": "Не удалось удалить профиль.",
  "profile.name": "Название профиля",
  "profile.city": "Город",
  "profile.postalCode": "Индекс",
  "profile.radius": "Радиус (км)",
  "profile.radiusPlaceholder": "напр. 10",
  "profile.namePlaceholder": "напр. Berlin Mitte 2-комн.",
  "profile.cityPlaceholder": "напр. Berlin",
  "profile.postalCodePlaceholder": "напр. 10115",
  "profile.autoCity": "Подставить город",
  "profile.nameRequired": "Название профиля обязательно",
  "profile.notFound": "Профиль не найден",
  "profile.loadError": "Не удалось загрузить профиль",
  "profile.updateError": "Не удалось обновить профиль",
  "profile.priceSpan": "Ценовой диапазон (€)",
  "profile.priceMin": "Цена (мин)",
  "profile.priceMax": "Цена (макс)",
  "profile.areaSpan": "Площадь (м²)",
  "profile.areaMin": "Площадь (мин)",
  "profile.areaMax": "Площадь (макс)",
  "profile.roomsMin": "Комнат (мин)",
  "profile.amenities": "Удобства",
  "profile.balcony": "Балкон",
  "profile.elevator": "Лифт",
  "profile.parking": "Парковка",
  "profile.parkingLabel": "Парковка / Гараж",
  "profile.pets": "Можно с животными",
  "profile.notify": "Уведомления включены",
  "profile.submit": "Сохранить профиль",
  "profile.submitting": "Сохранение...",
  "profile.cancel": "Отмена",
  "profile.createError": "Не удалось создать профиль",
  "profile.filtersRequired": "Выберите хотя бы один фильтр.",
  "profile.validationError": "Проверьте значения фильтров.",
  "profile.radiusIncomplete": "Для радиуса нужны Lat, Lng и значение радиуса.",
  "profile.geoHint":
    "Координаты центра подставляются автоматически из индекса (PLZ). Радиус задаёт, как далеко искать вокруг центра.",
  "profile.geoCenter": "Центр",
  "profile.numericFilters": "Критерии поиска",
  "profile.price": "Цена",
  "profile.area": "Площадь",
  "profile.rooms": "Комнат",
  "admin.title": "Панель администратора",
  "admin.stats.users": "Пользователи",
  "admin.stats.listings": "Квартиры",
  "admin.stats.matches": "Совпадения",
  "admin.stats.notifications": "Уведомления",
  "admin.sources": "Источники",
  "admin.sources.enabled": "Активен",
  "admin.sources.disabled": "Неактивен",
  "admin.sources.listingsCount": "Объявлений",
  "admin.queues": "Очереди",
  "admin.queues.collect": "Сбор",
  "admin.queues.match": "Сравнение",
  "admin.queues.notify": "Уведомления",
  "admin.logs": "Последние действия",
  "admin.logs.action": "Действие",
  "admin.logs.details": "Детали",
  "admin.logs.time": "Время",
  "admin.logs.empty": "Нет записей",
  "admin.loading": "Загрузка...",
  "admin.subtitle": "Обзор системы и управление",
  "admin.refresh": "Обновить",
  "admin.sources.empty": "Источники не настроены",
  "admin.sources.breaker": "Предохранитель",
  "admin.sources.lastRun": "Последний запуск",
  "admin.sources.lifecycle": "Жизненный цикл",
  "admin.sources.runStatus": "Статус",
  "admin.sources.fetched": "Получено",
  "admin.sources.new": "Новые",
  "admin.sources.updated": "Обновлено",
  "admin.sources.errors": "Ошибки",
  "admin.sources.noMetrics": "Нет данных о запусках",
  "admin.queues.depth": "Глубина",
  "admin.queues.waiting": "в ожидании",
  "admin.queues.delayed": "отложено",
  "admin.queues.failed": "с ошибкой",
  "admin.health.healthy": "Работает",
  "admin.health.degraded": "Ограниченно",
  "admin.health.failing": "Сбой",
  "admin.health.paused": "Пауза",
  "admin.health.unknown": "Неизвестно",
  "footer.text": "© SucheWohnung — поиск квартир в Германии",
  "footer.description": "Ваш помощник в поиске квартир в Германии",
  "footer.links": "Ссылки",
  "footer.contact": "Контакты",
  "footer.contactText": "По вопросам мы с радостью поможем.",
  "footer.copyright": "© {year} SucheWohnung. Все права защищены.",
  "common.loading": "Загрузка...",
  "common.error": "Ошибка",
  "common.save": "Сохранить",
  "common.active": "Активен",
  "common.inactive": "Неактивен",
  "common.all": "Все",
  "common.none": "Нет",
  "common.yes": "Да",
  "common.no": "Нет",
  "common.min": "Мин",
  "common.max": "Макс",
  "common.paused": "На паузе",
  "matches.title": "Найденные квартиры",
  "matches.empty": "Пока нет совпадений",
  "matches.price": "Цена",
  "matches.area": "Площадь",
  "matches.rooms": "Комнат",
  "matches.viewListing": "Смотреть",
} satisfies DictShape;

export type DictKey = keyof typeof de;

export const dict = { de, ru } as const;
